/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package httpclientexample;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.util.EntityUtils;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try {
            // Create an instance of HttpClient
            HttpClient httpClient = HttpClientBuilder.create().build();

            // Create an instance of HttpPost with the desired URL
            String postUrl = "http://example.com/api/endpoint";
            HttpPost httpPost = new HttpPost(postUrl);

            // Add headers to the request
            httpPost.setHeader("Content-type", "application/json");

            // Set the request body
            String request = "{\"name\":\"David\", \"age\":20}";
            StringEntity entity = new StringEntity(request);
            httpPost.setEntity(entity);

            // Execute the request and obtain the response
            HttpResponse httpResponse = httpClient.execute(httpPost);

            // Extract the response's content
            HttpEntity responseEntity = httpResponse.getEntity();
            String response = EntityUtils.toString(responseEntity);

            // Print the response
            System.out.println(response);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
